### ISSUE TITLE
Source Manager layout: HTTP headers layout broke

### ISSUE THREAD

**Issue by JanHoefelmeyer** [gocsaf/csaf#578]
See
![Screenshot 2024-10-07 at 07-42-22 Sources - Add source](https://github.com/user-attachments/assets/d8700a00-b473-4499-b0d2-5111a5f75a91)

**Comment by tschmidtb51** [comment]
@JanHoefelmeyer Wrong repo?

**Comment by bernhardreiter** [comment]
Wrong repo.
